stages:
  - test
  - build

test:
  stage: test
  services:
    - docker:dind
  image: python:3.10.10-slim
  tags:
    - docker
  script:
    - apt-get update -y
    - apt-get install -y git
    - pip install -r requirements.txt
    - pytest --junitxml=./report.xml
  artifacts:
    when: always
    reports:
      junit: "report.xml"
    expire_in: 2 weeks

build_dev:
  stage: build
  services:
    - docker:dind
  image: docker:dind
  except:
    - tags
    - main
  tags:
    - docker
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" docker-registry.itz.uni-halle.de
    - docker build --pull -t docker-registry.itz.uni-halle.de/elearning/opencast/ts-api:$CI_COMMIT_REF_NAME .
    - docker push docker-registry.itz.uni-halle.de/elearning/opencast/ts-api:$CI_COMMIT_REF_NAME

build:
  stage: build
  services:
    - docker:dind
  image: docker:dind
  only:
    - tags
  tags:
    - docker
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" docker-registry.itz.uni-halle.de
    - docker build --pull -t docker-registry.itz.uni-halle.de/elearning/opencast/ts-api:latest -t docker-registry.itz.uni-halle.de/elearning/opencast/ts-api:$CI_COMMIT_REF_NAME .
    - docker push docker-registry.itz.uni-halle.de/elearning/opencast/ts-api --all-tags